# Why do we build this?
# - to have an image which contains all build environment.
# And in in the container (docker-entrypoint.sh) we build it acutally
# to make sure that it works.

ARG RELEASE
FROM ${RELEASE} AS rstmap_angular_release
ARG RELEASE

#SHELL ["/bin/bash", "-cl"]


# Теперь нам надо заменить все содержимое каталога /app в образе на ./app из хоста (из dev версии) (Это если мы собираем локально
# а если на github actions то мы используем actions/checkout@v3 )
# WORKDIR /app
# RUN rm -Rf ./*
# COPY ./app .

#-----------------------------------------
# We could run in here but we should run in from the 'dev' version and
# copy resulting 'dist' folder here with the 'app' directory.

RUN npm install

RUN source $NVM_DIR/nvm.sh \
    && npm run-script buildprod
#-----------------------------------------

COPY docker-entrypoint.sh /usr/local/bin/


EXPOSE 4200

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["release"]


#-----------------------------------------




































