# Why do we build this?
# - to have an image which contains all build environment.
# And in in the container (docker-entrypoint.sh) we build it acutally
# to make sure that it works.

ARG RELEASE
FROM ${RELEASE} AS from_node_v_rel
ARG RELEASE

#SHELL ["/bin/bash", "-cl"]


# Now we need to replace all the contents of the /app directory in the image with ./app from the host (from the dev version)

# (We are going exactly in the image; we want to copy the app from the context here)
WORKDIR /app
RUN rm -Rf ./*

# (We are in the context /home/runner/work/RstMap_Angular/RstMap_Angular in this context there is an app, we copy it.)
COPY ./app .

#-----------------------------------------
# We could run in here but we should run in from the 'dev' version and
# copy resulting 'dist' folder here with the 'app' directory.

RUN pwd
RUN ls

RUN source $NVM_DIR/nvm.sh \
    && npm install


RUN ls

# RUN source $NVM_DIR/nvm.sh \
#     && npm run-script buildprod
#-----------------------------------------

COPY docker-entrypoint.sh /usr/local/bin/


EXPOSE 4200

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["release"]


#-----------------------------------------




































