FROM ubuntu:18.04 

# sets the Dockerfile's default shell to a bash login shell. 
# this means that every subsequent RUN, CMD, and ENTRYPOINT 
# will be run under the current user (usually root), 
# and source the ~/.bashrc file if run in the shell form.
SHELL ["/bin/bash", "--login", "-c"]

RUN apt-get update -y
RUN apt-get install -y lsb-release man wget curl nano software-properties-common gcc libssl-dev ca-certificates git apt-transport-https

ENV NVM_DIR /root/.nvm 
ENV NODE_VERSION 8.9.0


# Install nvm with node and npm
# RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.16.1/install.sh | sh
# RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.20.0/install.sh | bash
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
# RUN . $NVM_DIR/nvm.sh
# RUN nvm install 8.9.0
# RUN nvm alias default $NODE_VERSION
# RUN nvm use default

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/v$NODE_VERSION/bin:$PATH

ENTRYPOINT ["/bin/bash"]