name: TEST_CONTEXT

# on:
#   push:
#     branches:
#     - main
#     - release/*
#   workflow_dispatch:


on: [workflow_dispatch]

jobs:
  test_job1:
  steps:
    -name: Step 1
    run: echo "Step 1" 