name: BUILD_DOCKER_RELEASE_ON_PUSH

on:

  workflow_dispatch:
  
  push:
    branches:
    - main
    - release/*
    

jobs:
  build_docker:
    runs-on: ubuntu-latest
    # needs: [CONDUCTOR_BLOBBERS_01_TESTS]
