name: BUILD_DOCKER_RELEASE_ON_PUSH

on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:
    
    

jobs:
  build:
    runs-on: ubuntu-latest
    # needs: [CONDUCTOR_BLOBBERS_01_TESTS]
    steps:
      - name: Test step
        run: echo "Test step"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}   
