name: BUILD_DOCKER_RELEASE_ON_PUSH

on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:
    
    

jobs:
  build_docker:
    runs-on: ubuntu-latest
    # needs: [CONDUCTOR_BLOBBERS_01_TESTS]
