on:
  workflow_call:
    inputs:
      chain_branch:
        type: string
        description: 'Input branch for 0chain repo'
        default: 'default_value'
        required: false  
    # Map the workflow outputs to job outputs
    outputs:
      my_var:
        description: "The first output string"
        value: ${{jobs.my_job.outputs.my_var}}
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      my_var: ${{steps.my_step.outputs.my_var}}
    steps:
      - name: "Example output creation2"
        id: "my_step"
        run: |
          my_var="Hello World"
          echo "Output [$my_var]"
          echo "my_var=$my_var" >> $GITHUB_OUTPUT 
      - name: "Example output creation"
        id: "my_step2"
        run: |
          CHAIN_BRANCH="${{ inputs.chain_branch }}"
          echo  ${CHAIN_BRANCH} 

  my_second_job:
    runs-on: ubuntu-latest
    needs: my_job
    steps:
      - run: echo my_var [${{needs.my_job.outputs.my_var}}]